spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.cj.jdbc.Driver
          #基本属性
          url: jdbc:mysql://47.104.192.159:3306/spring-boot-vue?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: 1
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          # 用来检测连接是否有效的SQL，如果为null，test-on-borrow test-on-return test-while-idle都会失效
          validation-query: SELECT 'x'
          # 申请连接时候的检测 空闲时间大于 time-between-eviction-runs-millis 执行validation-query检测连接是否有效
          test-while-idle: true
          # 申请连接时执行 validation-query 检验连接是否有效，配置了会降低性能
          test-on-borrow: false
          # 归还连接时执行 validation-query 检验连接是否有效，配置了会降低性能
          test-on-return: false
          #打开PSCache。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          # 指定每个连接上PSCache的大小
          max-pool-prepared-statement-per-connection-size: 20
          # 设置自动重连，但是消耗性能
          # connection-error-retry-attempts: 0
          # break-after-acquire-failure: true
    main:
      allow-bean-definition-overriding: true
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 1234
